In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,4,5,6]], np.int32)

In [3]:
myarr

array([[3, 4, 5, 6]])

In [4]:
myarr=np.array([[3,4,55555,6]], np.int64)

In [5]:
myarr

array([[    3,     4, 55555,     6]], dtype=int64)

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0,1]=50

In [9]:
myarr

array([[    3,    50, 55555,     6]], dtype=int64)

# Array Creation-Conversion from other python structures


In [10]:
listarray=np.array([[1,2,3],[5,8,6],[0,3,1]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 8, 6],
       [0, 3, 1]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [19]:
zeros.size

10

In [20]:
rng=np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lnspace=np.linspace(1,50,10)

In [23]:
lnspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
emp=np.empty((4,6))

In [25]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.90098127e-307, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 6.23053614e-307, 2.22522597e-306,
        1.06810268e-306, 6.23052935e-307, 1.33511562e-306],
       [6.89805151e-307, 2.22522597e-306, 1.33511969e-306,
        8.90071135e-308, 8.45610231e-307, 2.18568966e-312]])

In [26]:
emplike=np.empty_like(lnspace)

In [27]:
emplike

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [28]:
ide=np.identity(50)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
arr=np.arange(50)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [33]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
arr.shape

(50,)

In [35]:
x=[[1,2,4],[3,5,6],[7,8,0]]

In [36]:
ar=np.array(x)

In [37]:
ar

array([[1, 2, 4],
       [3, 5, 6],
       [7, 8, 0]])

In [38]:
ar.sum(axis=1)

array([ 7, 14, 15])

In [39]:
ar.sum(axis=0)

array([11, 15, 10])

In [40]:
ar.T

array([[1, 3, 7],
       [2, 5, 8],
       [4, 6, 0]])

In [41]:
ar.flat

In [42]:
ar

array([[1, 2, 4],
       [3, 5, 6],
       [7, 8, 0]])

In [43]:
for item in ar.flat:
    print(item)

1
2
4
3
5
6
7
8
0


In [44]:
ar.ndim

2

In [45]:
ar.size

9

In [46]:
ar.shape

(3, 3)

In [47]:
ar.nbytes

36

In [48]:
one=np.array([0,2,8,40,6,3,4])

In [49]:
one


array([ 0,  2,  8, 40,  6,  3,  4])

In [50]:
one.argmax()

3

In [51]:
one.argmin()

0

In [52]:
ar

array([[1, 2, 4],
       [3, 5, 6],
       [7, 8, 0]])

In [53]:
ar.argmax()

7

In [54]:
ar.argmin()

8

In [55]:
ar.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [56]:
ar.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [57]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [58]:
ar2=np.array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]])

In [59]:
ar2

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]])

In [61]:
ar+ar2

array([[1, 3, 6],
       [3, 6, 8],
       [9, 8, 1]])

In [62]:
ar-ar2

array([[ 1,  1,  2],
       [ 3,  4,  4],
       [ 5,  8, -1]])

In [63]:
ar*ar2

array([[ 0,  2,  8],
       [ 0,  5, 12],
       [14,  0,  0]])

In [64]:
np.sqrt(ar)

array([[1.        , 1.41421356, 2.        ],
       [1.73205081, 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 0.        ]])

In [65]:
ar.sum()

36

In [66]:
ar.min()

0

In [67]:
ar.max()

8

In [71]:
np.where(ar>7)

(array([2], dtype=int64), array([1], dtype=int64))

In [72]:
type(np.where(ar>7))

tuple

In [73]:
np.count_nonzero(ar)

8

In [74]:
ar

array([[1, 2, 4],
       [3, 5, 6],
       [7, 8, 0]])

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [76]:
ar[1][2]=0

In [77]:
ar

array([[1, 2, 4],
       [3, 5, 0],
       [7, 8, 0]])

In [78]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [79]:
import sys


In [80]:
py_ar=[1,2,3,4]

In [82]:
nu_arr=np.array(py_ar)

In [83]:
nu_arr

array([1, 2, 3, 4])

In [85]:
sys.getsizeof(1)*len(py_ar)

112

In [89]:
nu_arr.itemsize*nu_arr.size

16

In [90]:
nu_arr.tolist()

[1, 2, 3, 4]